# Generated by Django 4.2.6 on 2023-11-25 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trashfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trashfile',
            options={'verbose_name_plural': 'Trash Files'},
        ),
        migrations.AddField(
            model_name='trashfile',
            name='file',
            field=models.FileField(default=None, upload_to='trashfiles/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trashfile',
            name='file_created',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trashfile',
            name='file_modified',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trashfile',
            name='file_size',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trashfile',
            name='file_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trashfile',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
