# Generated by Django 4.2.6 on 2023-11-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashfiles', '0002_alter_trashfile_options_trashfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashfile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
